---
name: Deploy Mulesoft Application
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup Java JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: oracle
          java-version: 17
          check-latest: false
          cache: maven
      - name: Maven verify
        run: mvn clean verify
      - name: Maven compile
        run: mvn clean compile
      - name: Maven package
        run: mvn -B package --file pom.xml
      - name: Stamp artifact file name with commit hash
        run: |
          artifactName1=$(ls target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
          mv $artifactName1 $artifactName2
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: target/*.jar
