---
name: Deploy Mulesoft Application
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Java JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'oracle'
          java-version: 17
          check-latest: false 
          cache: 'maven'
         
      - name: Maven verify
        run: mvn clean compile 

      - name: Build Mule application 
        run: mvn clean package 

  #    - name: Deploy to CloudHub 
   #     run: 
     #     curl -X POST\
     #     -F "file=@./target/mule-application.zip"\
     #     -F "username=$ANYPOINT_USERNAME"\
     #     -F "password=$ANYPOINT_PASSWORD"\
    #      https://anypoint.mulesoft.com/cloudhub/api/applications 
