---
name: Deploy Mulesoft Application
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup Java JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: oracle
          java-version: 17
          check-latest: false
          cache: maven
      - name: Maven verify
        run: mvn clean compile
      - name: Build Mule application
        run: mvn clean package
